modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/terrarium-earth/Handcrafted/issues"
license = "All Rights Reserved"

[[mods]]
modId = "handcrafted"
version = "${version}"
displayName = "Handcrafted"
authors = "Kekie, MsRandom, CodexAdrian, Alex Nijjar"
description = '''
Epic Furniture mod!
'''
#logoFile = ""

[[dependencies.handcrafted]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.handcrafted]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"